name: example
description: Example
publish_to: "none"
version: 0.0.8+79

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    version: ^0.0.0
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0

dev_dependencies:
  lint: ^2.2.0

flutter:
  uses-material-design: true

  # assets:
