name: log_reader
description: Reads log files and visualises them
publish_to: "none"
version: 3.0.1+77

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    version: ^0.0.0
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  fl_chart: ^0.65.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flash: ^3.1.0
  rxdart: ^0.27.7
  file_picker: ^6.1.1
  supercharged: ^2.1.1
  package_info_plus: ^5.0.1
  collection: ^1.18.0
  flutter_spinbox: ^0.13.1
  auto_size_text: ^3.0.0
  capped_progress_indicator: ^0.0.2
  shared_preferences: ^2.2.2
  desktop_drop: ^0.4.4
  cross_file: ^0.3.3+7
  github_version_checker:
    git:
      url: git@github.com:mike-500/github_version_checker
      ref: master


dev_dependencies:
  lint: ^2.2.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: false
  ios: false
  web:
    generate: false
  windows:
    generate: true
  macos:
    generate: true
  linux: false
  image_path: assets/icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - .git/HEAD
    - .git/refs/heads/master
